universe:
  - BTCUSDT
  - ETHUSDT
  - SOLUSDT
  - XRPUSDT
  - 1000PEPEUSDT
  - SEIUSDT
  - SUIUSDT
  - DOGEUSDT
  - NEWTUSDT
  - BNBUSDT
  - UNIUSDT
  - ADAUSDT
  - BANANAS31USDT
  - TRXUSDT
  - PENGUUSDT
  - APTUSDT
  - WIFUSDT
  - SYRUPUSDT
  - AAVEUSDT
  - ARBUSDT
  - VIRTUALUSDT
  - ENAUSDT
  - BCHUSDT
  - LINKUSDT
  - TAOUSDT
  - AVAXUSDT
  - PNUTUSDT
  - NEIROUSDT
  - FUNUSDT
  - LTCUSDT
  - PAXGUSDT
  - NEARUSDT
  - WLDUSDT
  - MOVEUSDT
  - SUSDT
  - FETUSDT
  - HBARUSDT
  - CRVUSDT
  - ETHFIUSDT
  - LPTUSDT
  - HIFIUSDT
  - WUSDT
  - BSWUSDT
  - DOTUSDT
  - RESOLVUSDT
  - ONDOUSDT
  - KAIAUSDT
  - MUBARAKUSDT
  - 1000FLOKIUSDT
  - 1000SHIBUSDT
  - SPKUSDT
  - TUTUSDT
  - AIXBTUSDT
  - RUNEUSDT
  - FILUSDT
  - EIGENUSDT
  - TONUSDT
  - PENDLEUSDT
  - FORMUSDT
  - BMTUSDT
  - GALAUSDT
  - LDOUSDT
  - XLMUSDT
  - BROCCOLI714USDT
  - JUPUSDT
  - RAREUSDT
  - DEXEUSDT
  - MKRUSDT
  - LQTYUSDT
  - COMPUSDT
  - INITUSDT
  - KAITOUSDT
  - POLUSDT
  - WCTUSDT
  - HUMAUSDT
  - CAKEUSDT
  - GPSUSDT
  - OMUSDT
  - ARUSDT
 
 